services:
  - type: web
    name: mylands-api
    runtime: docker

    plan: free

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: LOG_CHANNEL
        value: stack
