<?php
use App\Http\Controllers\{AuditLogController,AuthController,ContractController,CustomerAuthController,CustomerController,AdminActionCenterController,CustomerDocumentController,CustomerListingController,CustomerMediaController,CustomerNotificationController,CustomerProductController,CustomerProfileController,CustomerTransactionController,CustomerWalletController,DashboardController,DisputeController,DocumentTemplateController,GeneratedDocumentController,ListingController,MarketplaceController,PaymentController,ProductController,TransactionController,WalletAdminController,CustomerSecurityController,MarketplacePaymentSettingController,MarketplaceContractController,RuntimeController,CustomerPayoutController,PayoutAdminController,MarketplaceOperationsController,MarketplaceOperationsAdminController,MarketplaceTrustController,MarketplaceContentController,MarketplaceTrustAdminController};
use Illuminate\Support\Facades\Route;
Route::post('login',[AuthController::class,'login'])->middleware('throttle:10,1');
Route::post('refresh',[AuthController::class,'refresh'])->middleware('throttle:60,1');
Route::prefix('auth/customer')->group(function(){Route::post('forgot-password',[CustomerSecurityController::class,'forgotPassword'])->middleware('throttle:5,1');Route::post('reset-password',[CustomerSecurityController::class,'resetPassword'])->middleware('throttle:5,1');Route::post('verify-email',[CustomerSecurityController::class,'verifyEmailChange'])->middleware('throttle:10,1');Route::post('register',[CustomerAuthController::class,'register'])->middleware('throttle:10,1');Route::post('login',[CustomerAuthController::class,'login'])->middleware('throttle:10,1');Route::post('two-factor/verify',[CustomerAuthController::class,'verifyTwoFactor'])->middleware('throttle:10,1');Route::post('refresh',[CustomerAuthController::class,'refresh'])->middleware('throttle:60,1');Route::middleware('auth.customer')->group(function(){Route::get('me',[CustomerAuthController::class,'me']);Route::post('logout',[CustomerAuthController::class,'logout']);});});
Route::get('runtime', RuntimeController::class);
Route::get('marketplace-contract', MarketplaceContractController::class);
Route::get('marketplace/listings',[MarketplaceController::class,'index']);
Route::get('marketplace/listings/{listingCode}',[MarketplaceController::class,'show']);Route::get('marketplace/listings/{listing}/reviews',[MarketplaceContentController::class,'listingReviews']);Route::get('content',[MarketplaceContentController::class,'index']);Route::get('content/slug/{slug}',[MarketplaceContentController::class,'bySlug']);Route::get('content/{contentEntry}',[MarketplaceContentController::class,'show']);
Route::middleware('auth.customer')->prefix('customer')->group(function(){
 Route::put('profile',[CustomerProfileController::class,'update']);Route::post('profile/avatar',[CustomerProfileController::class,'updateAvatar'])->middleware('throttle:20,1');Route::post('profile/email-change',[CustomerSecurityController::class,'requestEmailChange'])->middleware('throttle:5,1');Route::put('profile/password',[CustomerSecurityController::class,'changePassword'])->middleware('throttle:5,1');Route::get('security/two-factor',[CustomerSecurityController::class,'twoFactorStatus']);Route::post('security/two-factor/setup',[CustomerSecurityController::class,'beginTwoFactorSetup'])->middleware('throttle:5,1');Route::post('security/two-factor/confirm',[CustomerSecurityController::class,'confirmTwoFactor'])->middleware('throttle:10,1');Route::post('security/two-factor/recovery-codes',[CustomerSecurityController::class,'regenerateRecoveryCodes'])->middleware('throttle:5,1');Route::delete('security/two-factor',[CustomerSecurityController::class,'disableTwoFactor'])->middleware('throttle:5,1');
 Route::post('media/images',[CustomerMediaController::class,'store'])->middleware('throttle:30,1');
 Route::get('products',[CustomerProductController::class,'index']);Route::post('products',[CustomerProductController::class,'store']);Route::put('products/{product}',[CustomerProductController::class,'update']);
 Route::get('listings',[CustomerListingController::class,'index']);Route::post('listings',[CustomerListingController::class,'store']);Route::put('listings/{listing}',[CustomerListingController::class,'update']);
 Route::get('transactions',[CustomerTransactionController::class,'index']);Route::get('transactions/{transaction}',[CustomerTransactionController::class,'show']);Route::post('listings/{listing}/transact',[CustomerTransactionController::class,'createFromListing']);Route::post('transactions/{transaction}/cancel',[CustomerTransactionController::class,'cancel']);Route::post('transactions/{transaction}/actions',[CustomerTransactionController::class,'action']);Route::get('transactions/{transaction}/payments/{payment}/qr',[CustomerTransactionController::class,'paymentQr']);Route::post('transactions/{transaction}/payments/{payment}/submit',[CustomerTransactionController::class,'submitPayment']);Route::post('transactions/{transaction}/disputes',[CustomerTransactionController::class,'openDispute']);
 Route::get('documents',[CustomerDocumentController::class,'index']);Route::get('transactions/{transaction}/documents',[CustomerDocumentController::class,'transactionDocuments']);Route::get('documents/{generatedDocument}/preview',[CustomerDocumentController::class,'preview']);Route::get('documents/{generatedDocument}/download',[CustomerDocumentController::class,'download']);Route::post('documents/{generatedDocument}/accept',[CustomerDocumentController::class,'accept']);
 Route::get('notifications',[CustomerNotificationController::class,'index']);Route::post('notifications/read-all',[CustomerNotificationController::class,'readAll']);Route::post('notifications/{notification}/read',[CustomerNotificationController::class,'read']);
 Route::get('wallet/transactions',[CustomerWalletController::class,'index']);Route::post('wallet/deposit/bank',[CustomerWalletController::class,'deposit']);Route::get('wallet/deposits/{walletTransaction}',[CustomerWalletController::class,'showDeposit']);Route::post('wallet/deposits/{walletTransaction}/proof',[CustomerWalletController::class,'submitProof']);
 Route::get('favorites',[MarketplaceTrustController::class,'favorites']);Route::post('favorites/{listing}',[MarketplaceTrustController::class,'favorite']);Route::delete('favorites/{listing}',[MarketplaceTrustController::class,'unfavorite']);Route::get('saved-searches',[MarketplaceTrustController::class,'savedSearches']);Route::post('saved-searches',[MarketplaceTrustController::class,'storeSavedSearch']);Route::delete('saved-searches/{savedSearch}',[MarketplaceTrustController::class,'deleteSavedSearch']);Route::get('reviews',[MarketplaceTrustController::class,'reviews']);Route::post('transactions/{transaction}/reviews',[MarketplaceTrustController::class,'storeReview']);Route::get('notification-preferences',[MarketplaceTrustController::class,'preferences']);Route::put('notification-preferences',[MarketplaceTrustController::class,'updatePreferences']);Route::get('sessions',[MarketplaceTrustController::class,'sessions']);Route::delete('sessions/{session}',[MarketplaceTrustController::class,'revokeSession']);
 Route::get('cases',[MarketplaceOperationsController::class,'cases']);Route::post('transactions/{transaction}/cases',[MarketplaceOperationsController::class,'openCase']);Route::post('cases/{case}/messages',[MarketplaceOperationsController::class,'message']);Route::get('transactions/{transaction}/asset-snapshots',[MarketplaceOperationsController::class,'snapshots']);Route::post('transactions/{transaction}/asset-snapshots',[MarketplaceOperationsController::class,'storeSnapshot']);
 Route::get('payouts',[CustomerPayoutController::class,'overview']);Route::post('seller-verification',[CustomerPayoutController::class,'submitVerification']);Route::post('payout-accounts',[CustomerPayoutController::class,'storeAccount']);Route::post('withdrawals',[CustomerPayoutController::class,'withdraw']);
});
Route::middleware('auth.api')->group(function(){
 Route::get('me',[AuthController::class,'me']);
 Route::get('audit-logs/statistics',[AuditLogController::class,'statistics']);Route::get('audit-logs',[AuditLogController::class,'index']);Route::get('audit-logs/{auditLog}',[AuditLogController::class,'show']);
Route::get('action-center',AdminActionCenterController::class);Route::post('logout',[AuthController::class,'logout']);Route::get('dashboard',DashboardController::class);
 Route::apiResource('document-templates',DocumentTemplateController::class);Route::get('generated-documents',[GeneratedDocumentController::class,'index']);Route::get('generated-documents/{generatedDocument}',[GeneratedDocumentController::class,'show']);Route::get('generated-documents/{generatedDocument}/preview',[GeneratedDocumentController::class,'preview']);Route::get('generated-documents/{generatedDocument}/download',[GeneratedDocumentController::class,'download']);Route::post('transactions/{transaction}/documents/ensure',[GeneratedDocumentController::class,'ensure']);Route::post('transactions/{transaction}/documents/generate',[GeneratedDocumentController::class,'generate']);
 Route::apiResource('products',ProductController::class);Route::apiResource('customers',CustomerController::class);Route::apiResource('transactions',TransactionController::class);Route::apiResource('contracts',ContractController::class);
 Route::post('transactions/{transaction}/actions',[TransactionController::class,'action']);
 Route::get('listings',[ListingController::class,'index']);Route::get('listings/{listing}',[ListingController::class,'show']);Route::post('listings/{listing}/approve',[ListingController::class,'approve']);Route::post('listings/{listing}/reject',[ListingController::class,'reject']);
 Route::get('payments',[PaymentController::class,'index']);Route::post('payments/{payment}/confirm',[PaymentController::class,'confirm']);Route::post('payments/{payment}/reject',[PaymentController::class,'reject']);
 Route::get('payment-settings',[MarketplacePaymentSettingController::class,'show']);Route::put('payment-settings',[MarketplacePaymentSettingController::class,'update']);Route::post('payment-settings/qr-preview',[MarketplacePaymentSettingController::class,'preview']);
 Route::get('wallets',[WalletAdminController::class,'wallets']);Route::get('wallets/{customer}',[WalletAdminController::class,'ledger']);Route::post('wallets/{customer}/adjust',[WalletAdminController::class,'adjust']);Route::get('wallet-deposits',[WalletAdminController::class,'index']);Route::post('wallet-deposits/{walletTransaction}/confirm',[WalletAdminController::class,'confirm']);Route::post('wallet-deposits/{walletTransaction}/reject',[WalletAdminController::class,'reject']);
 Route::get('disputes',[DisputeController::class,'index']);Route::get('disputes/{dispute}',[DisputeController::class,'show']);Route::post('disputes/{dispute}/resolve',[DisputeController::class,'resolve']);
 Route::get('marketplace-reviews',[MarketplaceTrustAdminController::class,'reviews']);Route::post('marketplace-reviews/{review}/moderate',[MarketplaceTrustAdminController::class,'moderateReview']);Route::get('content-entries',[MarketplaceTrustAdminController::class,'contents']);Route::post('content-entries',[MarketplaceTrustAdminController::class,'storeContent']);Route::put('content-entries/{contentEntry}',[MarketplaceTrustAdminController::class,'updateContent']);Route::get('risk-flags',[MarketplaceTrustAdminController::class,'risks']);Route::post('risk-flags/{riskFlag}/resolve',[MarketplaceTrustAdminController::class,'resolveRisk']);
 Route::get('fee-policies',[MarketplaceOperationsAdminController::class,'feePolicies']);Route::post('fee-policies',[MarketplaceOperationsAdminController::class,'storeFeePolicy']);Route::put('fee-policies/{policy}',[MarketplaceOperationsAdminController::class,'updateFeePolicy']);Route::get('marketplace-cases',[MarketplaceOperationsAdminController::class,'cases']);Route::get('marketplace-cases/{case}',[MarketplaceOperationsAdminController::class,'caseDetail']);Route::post('marketplace-cases/{case}/update',[MarketplaceOperationsAdminController::class,'updateCase']);Route::post('marketplace-cases/{case}/messages',[MarketplaceOperationsAdminController::class,'message']);Route::get('asset-snapshots',[MarketplaceOperationsAdminController::class,'snapshots']);
 Route::get('seller-verifications',[PayoutAdminController::class,'verifications']);Route::post('seller-verifications/{verification}/review',[PayoutAdminController::class,'reviewVerification']);Route::get('payout-accounts',[PayoutAdminController::class,'accounts']);Route::post('payout-accounts/{account}/review',[PayoutAdminController::class,'reviewAccount']);Route::get('withdrawals',[PayoutAdminController::class,'withdrawals']);Route::post('withdrawals/{withdrawal}/approve',[PayoutAdminController::class,'approve']);Route::post('withdrawals/{withdrawal}/reject',[PayoutAdminController::class,'reject']);Route::post('withdrawals/{withdrawal}/paid',[PayoutAdminController::class,'paid']);
});
