<?php

use App\Http\Controllers\AdminActionCenterController;
use App\Http\Controllers\AdminNotificationController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DisputeController;
use App\Http\Controllers\DocumentTemplateController;
use App\Http\Controllers\GeneratedDocumentController;
use App\Http\Controllers\MarketplaceOperationsAdminController;
use App\Http\Controllers\MarketplaceOperationsDashboardController;
use App\Http\Controllers\MarketplacePaymentSettingController;
use App\Http\Controllers\MarketplaceTrustAdminController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PayoutAdminController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WalletAdminController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth.api')->group(function () {
    Route::get('me', [AuthController::class, 'me']);
    Route::get('notifications', [AdminNotificationController::class, 'index']);
    Route::get('notifications/{notification}', [AdminNotificationController::class, 'show']);
    Route::post('notifications/read-all', [AdminNotificationController::class, 'readAll']);
    Route::post('notifications/{notification}/read', [AdminNotificationController::class, 'read']);
    Route::get('audit-logs/statistics', [AuditLogController::class, 'statistics']);
    Route::get('audit-logs', [AuditLogController::class, 'index']);
    Route::get('audit-logs/{auditLog}', [AuditLogController::class, 'show']);
    Route::get('action-center', AdminActionCenterController::class);
    Route::get('operations-dashboard/overview', [MarketplaceOperationsDashboardController::class, 'overview']);
    Route::get('operations-dashboard/holds', [MarketplaceOperationsDashboardController::class, 'holds']);
    Route::post('operations-dashboard/holds/{hold}/release', [MarketplaceOperationsDashboardController::class, 'releaseHold']);
    Route::get('operations-dashboard/products/{product}/availability-timeline', [MarketplaceOperationsDashboardController::class, 'availabilityTimeline']);
    Route::get('operations-dashboard/queues', [MarketplaceOperationsDashboardController::class, 'queues']);
    Route::get('operations-dashboard/idempotency', [MarketplaceOperationsDashboardController::class, 'idempotency']);
    Route::get('operations-dashboard/reconciliation', [MarketplaceOperationsDashboardController::class, 'reconciliation']);
    Route::get('operations-dashboard/rental-settlements', [MarketplaceOperationsDashboardController::class, 'rentalSettlements']);
    Route::get('operations-dashboard/rental-settlements/export', [MarketplaceOperationsDashboardController::class, 'exportRentalSettlements']);
    Route::post('operations-dashboard/rental-settlements/exports', [MarketplaceOperationsDashboardController::class, 'requestRentalSettlementExport']);
    Route::get('operations-dashboard/rental-settlements/exports/{exportRequest}', [MarketplaceOperationsDashboardController::class, 'rentalSettlementExportStatus']);
    Route::get('operations-dashboard/rental-settlements/exports/{exportRequest}/download', [MarketplaceOperationsDashboardController::class, 'downloadRentalSettlementExport']);
    Route::get('operations-dashboard/transactions/{transaction}/document-checklist', [MarketplaceOperationsDashboardController::class, 'documentChecklist']);
    Route::post('logout', [AuthController::class, 'logout']);
    Route::get('dashboard', DashboardController::class);
    Route::apiResource('document-templates', DocumentTemplateController::class);
    Route::get('generated-documents', [GeneratedDocumentController::class, 'index']);
    Route::get('generated-documents/{generatedDocument}', [GeneratedDocumentController::class, 'show']);
    Route::get('generated-documents/{generatedDocument}/preview', [GeneratedDocumentController::class, 'preview']);
    Route::get('generated-documents/{generatedDocument}/download', [GeneratedDocumentController::class, 'download']);
    Route::post('transactions/{transaction}/documents/ensure', [GeneratedDocumentController::class, 'ensure']);
    Route::post('transactions/{transaction}/documents/generate', [GeneratedDocumentController::class, 'generate']);
    Route::apiResource('products', ProductController::class);
    Route::post('products/{product}/approve', [ProductController::class, 'approve']);
    Route::post('products/{product}/reject', [ProductController::class, 'reject']);
    Route::apiResource('customers', CustomerController::class);
    Route::apiResource('transactions', TransactionController::class);
    Route::get('transactions/{transaction}/next-actions', [TransactionController::class, 'nextActions']);
    Route::post('transactions/{transaction}/actions', [TransactionController::class, 'action']);
    Route::get('payments', [PaymentController::class, 'index']);
    Route::post('payments/{payment}/confirm', [PaymentController::class, 'confirm']);
    Route::post('payments/{payment}/reject', [PaymentController::class, 'reject']);
    Route::get('payment-settings', [MarketplacePaymentSettingController::class, 'show']);
    Route::get('payment-settings/history', [MarketplacePaymentSettingController::class, 'history']);
    Route::put('payment-settings', [MarketplacePaymentSettingController::class, 'update']);
    Route::post('payment-settings/{paymentSetting}/activate', [MarketplacePaymentSettingController::class, 'activate']);
    Route::post('payment-settings/qr-preview', [MarketplacePaymentSettingController::class, 'preview']);
    Route::get('wallets', [WalletAdminController::class, 'wallets']);
    Route::get('wallets/{customer}', [WalletAdminController::class, 'ledger']);
    Route::post('wallets/{customer}/adjust', [WalletAdminController::class, 'adjust']);
    Route::get('wallet-deposits', [WalletAdminController::class, 'index']);
    Route::post('wallet-deposits/{walletTransaction}/confirm', [WalletAdminController::class, 'confirm']);
    Route::post('wallet-deposits/{walletTransaction}/reject', [WalletAdminController::class, 'reject']);
    Route::get('disputes', [DisputeController::class, 'index']);
    Route::get('disputes/{dispute}', [DisputeController::class, 'show']);
    Route::post('disputes/{dispute}/resolve', [DisputeController::class, 'resolve']);
    Route::get('marketplace-reviews', [MarketplaceTrustAdminController::class, 'reviews']);
    Route::post('marketplace-reviews/{review}/moderate', [MarketplaceTrustAdminController::class, 'moderateReview']);
    Route::get('content-entries', [MarketplaceTrustAdminController::class, 'contents']);
    Route::post('content-entries', [MarketplaceTrustAdminController::class, 'storeContent']);
    Route::put('content-entries/{contentEntry}', [MarketplaceTrustAdminController::class, 'updateContent']);
    Route::get('risk-flags', [MarketplaceTrustAdminController::class, 'risks']);
    Route::post('risk-flags/{riskFlag}/resolve', [MarketplaceTrustAdminController::class, 'resolveRisk']);
    Route::get('fee-policies', [MarketplaceOperationsAdminController::class, 'feePolicies']);
    Route::post('fee-policies', [MarketplaceOperationsAdminController::class, 'storeFeePolicy']);
    Route::put('fee-policies/{policy}', [MarketplaceOperationsAdminController::class, 'updateFeePolicy']);
    Route::get('marketplace-cases', [MarketplaceOperationsAdminController::class, 'cases']);
    Route::get('marketplace-cases/{case}', [MarketplaceOperationsAdminController::class, 'caseDetail']);
    Route::post('marketplace-cases/{case}/update', [MarketplaceOperationsAdminController::class, 'updateCase']);
    Route::post('marketplace-cases/{case}/messages', [MarketplaceOperationsAdminController::class, 'message']);
    Route::get('asset-snapshots', [MarketplaceOperationsAdminController::class, 'snapshots']);
    Route::get('seller-verifications', [PayoutAdminController::class, 'verifications']);
    Route::post('seller-verifications/{verification}/review', [PayoutAdminController::class, 'reviewVerification']);
    Route::get('payout-accounts', [PayoutAdminController::class, 'accounts']);
    Route::post('payout-accounts/{account}/review', [PayoutAdminController::class, 'reviewAccount']);
    Route::get('withdrawals', [PayoutAdminController::class, 'withdrawals']);
    Route::post('withdrawals/{withdrawal}/approve', [PayoutAdminController::class, 'approve']);
    Route::post('withdrawals/{withdrawal}/reject', [PayoutAdminController::class, 'reject']);
    Route::post('withdrawals/{withdrawal}/paid', [PayoutAdminController::class, 'paid']);
});
