<?php
use App\Http\Controllers\{AuditLogController,AuthController,ContractController,CustomerAuthController,CustomerController,AdminActionCenterController,CustomerDocumentController,CustomerListingController,CustomerMediaController,CustomerNotificationController,CustomerProductController,CustomerProfileController,CustomerTransactionController,CustomerWalletController,DashboardController,DisputeController,DocumentTemplateController,GeneratedDocumentController,ListingController,MarketplaceController,PaymentController,ProductController,TransactionController,WalletAdminController,CustomerSecurityController,MarketplacePaymentSettingController,MarketplaceContractController,RuntimeController,CustomerPayoutController,PayoutAdminController,MarketplaceOperationsController,MarketplaceOperationsAdminController,MarketplaceTrustController,MarketplaceContentController,MarketplaceTrustAdminController};
use Illuminate\Support\Facades\Route;
Route::middleware('auth.api')->group(function(){
 Route::get('me',[AuthController::class,'me']);
 Route::get('audit-logs/statistics',[AuditLogController::class,'statistics']);Route::get('audit-logs',[AuditLogController::class,'index']);Route::get('audit-logs/{auditLog}',[AuditLogController::class,'show']);
Route::get('action-center',AdminActionCenterController::class);Route::post('logout',[AuthController::class,'logout']);Route::get('dashboard',DashboardController::class);
 Route::apiResource('document-templates',DocumentTemplateController::class);Route::get('generated-documents',[GeneratedDocumentController::class,'index']);Route::get('generated-documents/{generatedDocument}',[GeneratedDocumentController::class,'show']);Route::get('generated-documents/{generatedDocument}/preview',[GeneratedDocumentController::class,'preview']);Route::get('generated-documents/{generatedDocument}/download',[GeneratedDocumentController::class,'download']);Route::post('transactions/{transaction}/documents/ensure',[GeneratedDocumentController::class,'ensure']);Route::post('transactions/{transaction}/documents/generate',[GeneratedDocumentController::class,'generate']);
 Route::apiResource('products',ProductController::class);Route::apiResource('customers',CustomerController::class);Route::apiResource('transactions',TransactionController::class);Route::apiResource('contracts',ContractController::class);
 Route::post('transactions/{transaction}/actions',[TransactionController::class,'action']);
 Route::get('listings',[ListingController::class,'index']);Route::get('listings/{listing}',[ListingController::class,'show']);Route::post('listings/{listing}/approve',[ListingController::class,'approve']);Route::post('listings/{listing}/reject',[ListingController::class,'reject']);
 Route::get('payments',[PaymentController::class,'index']);Route::post('payments/{payment}/confirm',[PaymentController::class,'confirm']);Route::post('payments/{payment}/reject',[PaymentController::class,'reject']);
 Route::get('payment-settings',[MarketplacePaymentSettingController::class,'show']);Route::get('payment-settings/history',[MarketplacePaymentSettingController::class,'history']);Route::put('payment-settings',[MarketplacePaymentSettingController::class,'update']);Route::post('payment-settings/{paymentSetting}/activate',[MarketplacePaymentSettingController::class,'activate']);Route::post('payment-settings/qr-preview',[MarketplacePaymentSettingController::class,'preview']);
 Route::get('wallets',[WalletAdminController::class,'wallets']);Route::get('wallets/{customer}',[WalletAdminController::class,'ledger']);Route::post('wallets/{customer}/adjust',[WalletAdminController::class,'adjust']);Route::get('wallet-deposits',[WalletAdminController::class,'index']);Route::post('wallet-deposits/{walletTransaction}/confirm',[WalletAdminController::class,'confirm']);Route::post('wallet-deposits/{walletTransaction}/reject',[WalletAdminController::class,'reject']);
 Route::get('disputes',[DisputeController::class,'index']);Route::get('disputes/{dispute}',[DisputeController::class,'show']);Route::post('disputes/{dispute}/resolve',[DisputeController::class,'resolve']);
 Route::get('marketplace-reviews',[MarketplaceTrustAdminController::class,'reviews']);Route::post('marketplace-reviews/{review}/moderate',[MarketplaceTrustAdminController::class,'moderateReview']);Route::get('content-entries',[MarketplaceTrustAdminController::class,'contents']);Route::post('content-entries',[MarketplaceTrustAdminController::class,'storeContent']);Route::put('content-entries/{contentEntry}',[MarketplaceTrustAdminController::class,'updateContent']);Route::get('risk-flags',[MarketplaceTrustAdminController::class,'risks']);Route::post('risk-flags/{riskFlag}/resolve',[MarketplaceTrustAdminController::class,'resolveRisk']);
 Route::get('fee-policies',[MarketplaceOperationsAdminController::class,'feePolicies']);Route::post('fee-policies',[MarketplaceOperationsAdminController::class,'storeFeePolicy']);Route::put('fee-policies/{policy}',[MarketplaceOperationsAdminController::class,'updateFeePolicy']);Route::get('marketplace-cases',[MarketplaceOperationsAdminController::class,'cases']);Route::get('marketplace-cases/{case}',[MarketplaceOperationsAdminController::class,'caseDetail']);Route::post('marketplace-cases/{case}/update',[MarketplaceOperationsAdminController::class,'updateCase']);Route::post('marketplace-cases/{case}/messages',[MarketplaceOperationsAdminController::class,'message']);Route::get('asset-snapshots',[MarketplaceOperationsAdminController::class,'snapshots']);
 Route::get('seller-verifications',[PayoutAdminController::class,'verifications']);Route::post('seller-verifications/{verification}/review',[PayoutAdminController::class,'reviewVerification']);Route::get('payout-accounts',[PayoutAdminController::class,'accounts']);Route::post('payout-accounts/{account}/review',[PayoutAdminController::class,'reviewAccount']);Route::get('withdrawals',[PayoutAdminController::class,'withdrawals']);Route::post('withdrawals/{withdrawal}/approve',[PayoutAdminController::class,'approve']);Route::post('withdrawals/{withdrawal}/reject',[PayoutAdminController::class,'reject']);Route::post('withdrawals/{withdrawal}/paid',[PayoutAdminController::class,'paid']);
});
