<?php
use App\Http\Controllers\{AuditLogController,AuthController,ContractController,CustomerAuthController,CustomerController,AdminActionCenterController,CustomerDocumentController,CustomerListingController,CustomerMediaController,CustomerNotificationController,CustomerProductController,CustomerProfileController,CustomerTransactionController,CustomerWalletController,DashboardController,DisputeController,DocumentTemplateController,GeneratedDocumentController,ListingController,MarketplaceController,PaymentController,ProductController,TransactionController,WalletAdminController,CustomerSecurityController,MarketplacePaymentSettingController,MarketplaceContractController,RuntimeController,CustomerPayoutController,PayoutAdminController,MarketplaceOperationsController,MarketplaceOperationsAdminController,MarketplaceTrustController,MarketplaceContentController,MarketplaceTrustAdminController};
use Illuminate\Support\Facades\Route;
Route::middleware('auth.customer')->prefix('customer')->group(function(){
 Route::put('profile',[CustomerProfileController::class,'update']);Route::post('profile/avatar',[CustomerProfileController::class,'updateAvatar'])->middleware('throttle:20,1');Route::post('profile/email-change',[CustomerSecurityController::class,'requestEmailChange'])->middleware('throttle:5,1');Route::put('profile/password',[CustomerSecurityController::class,'changePassword'])->middleware('throttle:5,1');Route::get('security/two-factor',[CustomerSecurityController::class,'twoFactorStatus']);Route::post('security/two-factor/setup',[CustomerSecurityController::class,'beginTwoFactorSetup'])->middleware('throttle:5,1');Route::post('security/two-factor/confirm',[CustomerSecurityController::class,'confirmTwoFactor'])->middleware('throttle:10,1');Route::post('security/two-factor/recovery-codes',[CustomerSecurityController::class,'regenerateRecoveryCodes'])->middleware('throttle:5,1');Route::delete('security/two-factor',[CustomerSecurityController::class,'disableTwoFactor'])->middleware('throttle:5,1');
 Route::post('media/images',[CustomerMediaController::class,'store'])->middleware('throttle:30,1');
 Route::get('products',[CustomerProductController::class,'index']);Route::post('products',[CustomerProductController::class,'store']);Route::put('products/{product}',[CustomerProductController::class,'update']);
 Route::get('listings',[CustomerListingController::class,'index']);Route::post('listings',[CustomerListingController::class,'store']);Route::put('listings/{listing}',[CustomerListingController::class,'update']);
 Route::get('transactions',[CustomerTransactionController::class,'index']);Route::get('transactions/{transaction}',[CustomerTransactionController::class,'show']);Route::post('listings/{listing}/transact',[CustomerTransactionController::class,'createFromListing']);Route::post('transactions/{transaction}/actions',[CustomerTransactionController::class,'action']);Route::get('transactions/{transaction}/payments/{payment}/qr',[CustomerTransactionController::class,'paymentQr']);Route::post('transactions/{transaction}/payments/{payment}/submit',[CustomerTransactionController::class,'submitPayment']);Route::post('transactions/{transaction}/disputes',[CustomerTransactionController::class,'openDispute']);
 Route::get('documents',[CustomerDocumentController::class,'index']);Route::get('transactions/{transaction}/documents',[CustomerDocumentController::class,'transactionDocuments']);Route::get('documents/{generatedDocument}/preview',[CustomerDocumentController::class,'preview']);Route::get('documents/{generatedDocument}/download',[CustomerDocumentController::class,'download']);Route::post('documents/{generatedDocument}/accept',[CustomerDocumentController::class,'accept']);
 Route::get('notifications',[CustomerNotificationController::class,'index']);Route::post('notifications/read-all',[CustomerNotificationController::class,'readAll']);Route::post('notifications/{notification}/read',[CustomerNotificationController::class,'read']);
 Route::get('wallet/transactions',[CustomerWalletController::class,'index']);Route::get('wallet/deposits',[CustomerWalletController::class,'deposits']);Route::post('wallet/deposit/bank',[CustomerWalletController::class,'deposit']);Route::get('wallet/deposits/{walletTransaction}',[CustomerWalletController::class,'showDeposit']);Route::post('wallet/deposits/{walletTransaction}/proof',[CustomerWalletController::class,'submitProof']);
 Route::get('favorites',[MarketplaceTrustController::class,'favorites']);Route::post('favorites/{listing}',[MarketplaceTrustController::class,'favorite']);Route::delete('favorites/{listing}',[MarketplaceTrustController::class,'unfavorite']);Route::get('saved-searches',[MarketplaceTrustController::class,'savedSearches']);Route::post('saved-searches',[MarketplaceTrustController::class,'storeSavedSearch']);Route::delete('saved-searches/{savedSearch}',[MarketplaceTrustController::class,'deleteSavedSearch']);Route::get('reviews',[MarketplaceTrustController::class,'reviews']);Route::post('transactions/{transaction}/reviews',[MarketplaceTrustController::class,'storeReview']);Route::get('notification-preferences',[MarketplaceTrustController::class,'preferences']);Route::put('notification-preferences',[MarketplaceTrustController::class,'updatePreferences']);Route::get('sessions',[MarketplaceTrustController::class,'sessions']);Route::delete('sessions/{session}',[MarketplaceTrustController::class,'revokeSession']);
 Route::get('cases',[MarketplaceOperationsController::class,'cases']);Route::get('cases/{case}',[MarketplaceOperationsController::class,'caseDetail']);Route::post('transactions/{transaction}/cases',[MarketplaceOperationsController::class,'openCase']);Route::post('cases/{case}/messages',[MarketplaceOperationsController::class,'message']);Route::get('transactions/{transaction}/asset-snapshots',[MarketplaceOperationsController::class,'snapshots']);Route::post('transactions/{transaction}/asset-snapshots',[MarketplaceOperationsController::class,'storeSnapshot']);
 Route::get('payouts',[CustomerPayoutController::class,'overview']);Route::post('seller-verification',[CustomerPayoutController::class,'submitVerification']);Route::post('payout-accounts',[CustomerPayoutController::class,'storeAccount']);Route::post('withdrawals',[CustomerPayoutController::class,'withdraw']);
});
