<?php
namespace App\Http\Controllers;
use App\Models\{CustomerPayoutAccount,CustomerVerification,CustomerWallet,WithdrawalRequest};
use App\Services\Payouts\WithdrawalService;
use App\Services\MediaUploadService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class CustomerPayoutController extends Controller {
 public function overview(){ $id=auth('customer_api')->id(); return success_response(['wallet'=>CustomerWallet::firstOrCreate(['customer_id'=>$id]),'verification'=>CustomerVerification::firstOrCreate(['customer_id'=>$id],['status'=>'unverified']),'accounts'=>CustomerPayoutAccount::where('customer_id',$id)->latest()->get(),'withdrawals'=>WithdrawalRequest::with('payoutAccount')->where('customer_id',$id)->latest()->paginate(20)]); }
 public function submitVerification(Request $r,MediaUploadService $media){$d=$r->validate(['document_type'=>'required|in:citizen_id,passport','document_number'=>'required|string|max:80','document_front'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120','document_back'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120','selfie'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120']);$id=auth('customer_api')->id();$item=CustomerVerification::firstOrCreate(['customer_id'=>$id]);if($item->status==='verified')return success_response($item);$front=$media->storeMany([$d['document_front']],'marketplace/customer-verifications')[0]['url'];$back=isset($d['document_back'])?$media->storeMany([$d['document_back']],'marketplace/customer-verifications')[0]['url']:null;$selfie=$media->storeMany([$d['selfie']],'marketplace/customer-verifications')[0]['url'];$item->update(['document_type'=>$d['document_type'],'document_number'=>$d['document_number'],'document_front_url'=>$front,'document_back_url'=>$back,'selfie_url'=>$selfie,'status'=>'pending','submitted_at'=>now(),'verified_at'=>null,'verified_by'=>null,'review_note'=>null]);return success_response($item->fresh(),'Đã gửi hồ sơ xác minh.');}
 public function storeAccount(Request $r){$d=$r->validate(['bank_code'=>'required|string|max:30','bank_name'=>'required|string|max:120','account_name'=>'required|string|max:150','account_number'=>'required|string|max:80','is_default'=>'sometimes|boolean']);$id=auth('customer_api')->id();return DB::transaction(function()use($d,$id){if(!empty($d['is_default']))CustomerPayoutAccount::where('customer_id',$id)->update(['is_default'=>false]);$item=CustomerPayoutAccount::create([...$d,'customer_id'=>$id,'status'=>'pending']);return success_response($item,'Đã thêm tài khoản nhận tiền.',201);});}
 public function withdraw(Request $r,WithdrawalService $service){$d=$r->validate(['payout_account_id'=>'required|integer','amount'=>'required|numeric|min:50000','note'=>'nullable|string|max:1000','idempotency_key'=>'nullable|string|max:150']);return success_response($service->submit(auth('customer_api')->id(),(int)$d['payout_account_id'],(string)$d['amount'],$d['note']??null,$d['idempotency_key']??null),'Đã gửi yêu cầu rút tiền.',201);}
}
