<?php
namespace App\Http\Controllers;
use App\Models\{CustomerWallet,WalletTransaction};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use App\Services\Payments\MarketplaceQrService;
class CustomerWalletController extends Controller {
 public function index(Request $r){$id=auth('customer_api')->id();$wallet=CustomerWallet::firstOrCreate(['customer_id'=>$id]);$q=WalletTransaction::where('customer_id',$id)->when($r->type,fn($q,$v)=>$q->where('type',$v))->when($r->status,fn($q,$v)=>$q->where('status',$v))->when($r->transaction_id,fn($q,$v)=>$q->where('transaction_id',$v))->latest('occurred_at')->latest();$items=$q->paginate(min(100,max(1,$r->integer('per_page',20))));return success_response(['wallet'=>['available_balance'=>$wallet->available_balance,'held_balance'=>$wallet->held_balance,'total_balance'=>bcadd((string)$wallet->available_balance,(string)$wallet->held_balance,2),'lifetime_credit'=>$wallet->lifetime_credit,'lifetime_debit'=>$wallet->lifetime_debit],'transactions'=>$items]);}
 public function deposit(Request $r,MarketplaceQrService $qrService){$d=$r->validate(['amount'=>'required|numeric|min:10000|max:100000000','payment_method'=>'required|in:bank,momo','note'=>'nullable|string|max:1000']);$id=auth('customer_api')->id();$wallet=CustomerWallet::firstOrCreate(['customer_id'=>$id]);$code='NAP-'.now()->format('ymd').'-'.strtoupper(Str::random(6));$payment=$qrService->make($code,$d['amount']);$m=WalletTransaction::create(['code'=>$code,'idempotency_key'=>'deposit:'.$id.':'.Str::uuid(),'customer_id'=>$id,'type'=>'deposit_request','direction'=>'credit','balance_bucket'=>'available','amount'=>$d['amount'],'available_before'=>$wallet->available_balance,'available_after'=>$wallet->available_balance,'held_before'=>$wallet->held_balance,'held_after'=>$wallet->held_balance,'balance_after'=>$wallet->available_balance,'status'=>'draft','payment_method'=>$d['payment_method'],'external_reference'=>$payment['transfer_content'],'metadata'=>$payment,'note'=>$d['note']??null,'occurred_at'=>now()]);return success_response($m->fresh(),'Đã tạo yêu cầu nạp tiền.',201);}
 public function showDeposit(WalletTransaction $walletTransaction){abort_unless($walletTransaction->customer_id===auth('customer_api')->id()&&$walletTransaction->type==='deposit_request',404);return success_response($walletTransaction);}
 public function submitProof(Request $r,WalletTransaction $walletTransaction){abort_unless($walletTransaction->customer_id===auth('customer_api')->id()&&$walletTransaction->type==='deposit_request',404);if(!in_array($walletTransaction->status,['draft','rejected'],true))throw ValidationException::withMessages(['status'=>'Yêu cầu nạp tiền không thể gửi lại ở trạng thái hiện tại.']);$d=$r->validate(['proof'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120','external_reference'=>'nullable|string|max:150','note'=>'nullable|string|max:1000']);$path=$d['proof']->store('marketplace/deposit-proofs','public');$walletTransaction->update(['proof_image_url'=>Storage::disk('public')->url($path),'external_reference'=>$d['external_reference']??$walletTransaction->external_reference,'note'=>$d['note']??$walletTransaction->note,'status'=>'submitted','submitted_at'=>now(),'review_note'=>null]);return success_response($walletTransaction->fresh(),'Đã gửi chứng từ. Yêu cầu đang chờ đối soát.');}
}
