<?php
namespace App\Http\Controllers;
use App\Models\{MarketplaceCaseMessage,MarketplaceDispute,Transaction,TransactionAssetSnapshot};
use App\Services\Marketplace\TransactionLifecycleService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class MarketplaceOperationsController extends Controller {
 public function cases(Request $r){$id=auth('customer_api')->id();$q=MarketplaceDispute::with(['transaction:id,code,status','messages'=>fn($q)=>$q->where('is_internal',false)->latest()])->whereHas('transaction',fn($q)=>$q->where('buyer_customer_id',$id)->orWhere('seller_customer_id',$id))->latest();return success_response($q->paginate(min(50,max(1,$r->integer('per_page',20)))));}
 public function caseDetail(MarketplaceDispute $case){$id=auth('customer_api')->id();$case->load(['transaction:id,code,status,product_id,buyer_customer_id,seller_customer_id','transaction.product:id,name','messages'=>fn($q)=>$q->where('is_internal',false)->oldest()]);abort_unless(in_array($id,[$case->transaction->buyer_customer_id,$case->transaction->seller_customer_id],true),403);return success_response($case);}
 public function openCase(Request $r,Transaction $transaction,TransactionLifecycleService $service){$id=auth('customer_api')->id();abort_unless(in_array($id,[$transaction->buyer_customer_id,$transaction->seller_customer_id],true),403);$d=$r->validate(['case_type'=>'required|in:support,cancellation,refund,handover_issue,return_issue,payment_issue,dispute,appeal','reason'=>'required|string|max:80','description'=>'required|string|max:4000','evidence'=>'nullable|array','priority'=>'nullable|in:low,normal,high,urgent']);return DB::transaction(function()use($d,$transaction,$id,$service){$case=MarketplaceDispute::create(['code'=>'CASE-'.strtoupper(Str::random(10)),'transaction_id'=>$transaction->id,'opened_by_customer_id'=>$id,'case_type'=>$d['case_type'],'reason'=>$d['reason'],'description'=>$d['description'],'evidence'=>$d['evidence']??[],'priority'=>$d['priority']??'normal','status'=>'open','due_at'=>now()->addHours(in_array($d['priority']??'normal',['high','urgent'],true)?24:72),'last_message_at'=>now()]);MarketplaceCaseMessage::create(['case_id'=>$case->id,'actor_type'=>'customer','actor_id'=>$id,'message'=>$d['description'],'attachments'=>$d['evidence']??[]]);if($d['case_type']==='dispute')$transaction->update(['status'=>'disputed']);$service->event($transaction,'case_opened','customer',$id,'Đã mở yêu cầu '.$case->code,$d['description'],['case_type'=>$d['case_type']]);return success_response($case->fresh(['transaction','messages']),'Đã gửi yêu cầu.',201);});}
 public function message(Request $r,MarketplaceDispute $case){$id=auth('customer_api')->id();abort_unless(in_array($id,[$case->transaction->buyer_customer_id,$case->transaction->seller_customer_id],true),403);$d=$r->validate(['message'=>'required|string|max:4000','attachments'=>'nullable|array']);$item=MarketplaceCaseMessage::create(['case_id'=>$case->id,'actor_type'=>'customer','actor_id'=>$id,'message'=>$d['message'],'attachments'=>$d['attachments']??[]]);$case->update(['last_message_at'=>now(),'status'=>in_array($case->status,['resolved','rejected','cancelled'],true)?'open':$case->status]);return success_response($item,'Đã gửi phản hồi.',201);}
 public function snapshots(Transaction $transaction){$id=auth('customer_api')->id();abort_unless(in_array($id,[$transaction->buyer_customer_id,$transaction->seller_customer_id],true),403);return success_response($transaction->assetSnapshots()->latest('captured_at')->get());}
 public function storeSnapshot(Request $r,Transaction $transaction){$id=auth('customer_api')->id();abort_unless(in_array($id,[$transaction->buyer_customer_id,$transaction->seller_customer_id],true),403);$d=$r->validate(['stage'=>'required|in:before_handover,after_handover,before_return,after_return','images'=>'required|array|min:1|max:10','images.*'=>'string|max:500','attributes'=>'nullable|array','note'=>'nullable|string|max:2000']);$item=TransactionAssetSnapshot::updateOrCreate(['transaction_id'=>$transaction->id,'stage'=>$d['stage'],'actor_type'=>'customer','actor_id'=>$id],[...$d,'customer_id'=>$id,'captured_at'=>now()]);return success_response($item,'Đã lưu biên bản hiện trạng.');}
}
