<?php
namespace App\Http\Controllers;
use App\Models\{Customer,CustomerWallet,WalletTransaction};
use App\Services\Wallet\WalletLedgerService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class WalletAdminController extends Controller {
 public function index(Request $r){$q=WalletTransaction::with('customer:id,code,name,username')->where('type','deposit_request')->when($r->status,fn($q,$v)=>$q->where('status',$v))->when($r->type,fn($q,$v)=>$q->where('type',$v))->latest();return success_response($q->paginate(min(100,max(1,$r->integer('per_page',20)))));}
 public function wallets(Request $r){$q=Customer::with('wallet')->when($r->keyword,fn($q,$v)=>$q->where(fn($w)=>$w->where('name','like',"%$v%")->orWhere('username','like',"%$v%")->orWhere('code','like',"%$v%")))->orderBy('name');return success_response($q->paginate(min(100,max(1,$r->integer('per_page',20)))));}
 public function ledger(Request $r,Customer $customer){$wallet=CustomerWallet::firstOrCreate(['customer_id'=>$customer->id]);$items=WalletTransaction::where('customer_id',$customer->id)->latest('occurred_at')->latest()->paginate(min(100,max(1,$r->integer('per_page',50))));return success_response(['customer'=>$customer->only(['id','code','name','username']),'wallet'=>$wallet,'transactions'=>$items]);}
 public function adjust(Request $r,Customer $customer,WalletLedgerService $ledger){$d=$r->validate(['direction'=>'required|in:credit,debit','bucket'=>'required|in:available,held','amount'=>'required|numeric|min:1','note'=>'required|string|max:1000']);$method=$d['direction']==='credit'?($d['bucket']==='held'?'creditHeld':'creditAvailable'):($d['bucket']==='held'?'debitHeld':'debitAvailable');$entry=$ledger->{$method}($customer->id,(string)$d['amount'],'admin_adjustment',['idempotency_key'=>'admin-adjust:'.Str::uuid(),'confirmed_by'=>user_id(),'note'=>$d['note'],'metadata'=>['admin_id'=>user_id()]]);return success_response($entry);}
 public function confirm(WalletTransaction $walletTransaction,WalletLedgerService $ledger){return DB::transaction(function()use($walletTransaction,$ledger){$entry=WalletTransaction::lockForUpdate()->findOrFail($walletTransaction->id);if($entry->status==='confirmed')return success_response($entry->fresh('customer'));if(!in_array($entry->status,['pending','submitted'],true)||$entry->type!=='deposit_request')throw ValidationException::withMessages(['status'=>'Yêu cầu nạp tiền không còn ở trạng thái chờ xác nhận.']);$credit=$ledger->creditAvailable($entry->customer_id,(string)$entry->amount,'deposit_confirmed',['idempotency_key'=>'deposit-confirm:'.$entry->id,'payment_method'=>$entry->payment_method,'external_reference'=>$entry->external_reference,'reference_type'=>'wallet_deposit','reference_id'=>$entry->id,'confirmed_by'=>user_id(),'note'=>$entry->note]);$entry->update(['status'=>'confirmed','review_note'=>null,'available_before'=>$credit->available_before,'available_after'=>$credit->available_after,'held_before'=>$credit->held_before,'held_after'=>$credit->held_after,'balance_after'=>$credit->available_after,'confirmed_at'=>now(),'confirmed_by'=>user_id()]);return success_response($entry->fresh('customer'));});}
 public function reject(Request $r,WalletTransaction $walletTransaction){$d=$r->validate(['note'=>'required|string|max:2000']);abort_unless(in_array($walletTransaction->status,['pending','submitted'],true),422);$walletTransaction->update(['status'=>'rejected','review_note'=>$d['note'],'confirmed_at'=>now(),'confirmed_by'=>user_id()]);return success_response($walletTransaction->fresh('customer'));}
}
